---
- name: Setup Jenkins and Docker on AWS
  hosts: all
  become: yes
  remote_user: ubuntu
  vars:
    ansible_ssh_private_key_file: "../my-key-pair.pem"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: ubuntu
  roles:
    - docker
    - jenkins
    - minikube
    - common
